- name: Base setup
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install base packages
      apt:
        name:
          - git
          - curl
          - vim
          - ufw
          - wget
          - tar
        state: present

    - name: Enable firewall
      ufw:
        state: enabled
        policy: allow

- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Download Docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Run Docker install script
      shell: sh /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes


- name: Setup monitoring stack
  hosts: monitor
  become: yes
  tasks:
    - name: Install Docker Compose plugin
      apt:
        name: docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure /opt/monitoring folder exists
      file:
        path: /opt/monitoring
        state: directory

    - name: Create prometheus config folder
      file:
        path: /opt/monitoring/prometheus
        state: directory

    - name: Copy prometheus config
      copy:
        dest: /opt/monitoring/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'node_exporter'
              static_configs:
                - targets: ['192.168.56.11:9100']

            - job_name: 'nginx_prometheus_exporter'
              metrics_path: /metrics
              static_configs:
                - targets: ['192.168.56.11:9113']
        owner: root
        group: root
        mode: '0644'

    - name: Copy docker-compose.yml
      copy:
        dest: /opt/monitoring/docker-compose.yml
        content: |
          services:
            prometheus:
              image: prom/prometheus
              container_name: monitoring_prometheus
              ports:
                - "9090:9090"
              volumes:
                - /opt/monitoring/prometheus:/etc/prometheus

            grafana:
              image: grafana/grafana
              container_name: monitoring_grafana
              ports:
                - "3000:3000"

        owner: root
        group: root
        mode: '0644'

    - name: Start monitoring stack
      shell: docker compose up -d
      args:
        chdir: /opt/monitoring


- name: Setup web server with Nginx, node_exporter, nginx_exporter and Promtail
  hosts: web-server
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create website directory
      file:
        path: "/var/www/website"
        state: directory
        mode: '0755'
    
    - name: Copy custom website
      copy:
        src: "./website/"
        dest: /var/www/website/
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Remove default config file if exists
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Copy custom Nginx config
      copy:
        dest: /etc/nginx/sites-available/my_site
        content: |
          server {
              listen 8081;
              server_name _;

              root /var/www/website;
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }

              location /nginx_status {
                  stub_status;
                  allow 127.0.0.1;
                  allow 192.168.56.9/30;
                  deny all;
              }
          }
        owner: root
        group: root
        mode: '0644'

    - name: Enable my_site
      file:
        src: /etc/nginx/sites-available/my_site
        dest: /etc/nginx/sites-enabled/my_site
        state: link


    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Fail if Nginx configuration is invalid
      fail:
        msg: "Nginx config test failed"
      when: nginx_test.rc != 0

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Run nginx-prometheus-exporter
      docker_container:
        name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - 9113:9113
        command: -nginx.scrape-uri http://127.0.0.1:8081/nginx_status

    - name: Reload nginx-prometheus-exporter
      shell: |
        docker rm -f nginx-exporter
        docker run -d --name nginx-exporter \
        --network host \
        nginx/nginx-prometheus-exporter:latest \
        -nginx.scrape-uri http://127.0.0.1:8081/nginx_status

    - name: Download node_exporter
      shell: |
        cd /opt
        sudo wget -q https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
        sudo tar xvf node_exporter-*.tar.gz
        sudo mv node_exporter-1.8.1.linux-amd64 node_exporter
        sudo rm node_exporter-*.tar.gz
      args:
        creates: /opt/node_exporter/node_exporter

    - name: Create systemd service for node_exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User=root
          ExecStart=/opt/node_exporter/node_exporter --web.listen-address=:9100

          [Install]
          WantedBy=default.target

    - name: Reload and enable node_exporter
      systemd:
        daemon_reload: yes
        name: node_exporter
        enabled: yes
        state: started

